### ISSUE TITLE
Download of hosted packages does not work due to wrong path

### ISSUE THREAD

**Issue by lioman** [sonatype-nexus-community/nexus-repository-conan#30]
* **What are you trying to do?**
Use the hosted repository "the conan way" by uploading and downloading packages.

## Reproduction Steps
- 2 repositories
  1. _conan_ (hosted)
  2. _conan-proxy_ (Proxy of conan-central)
- minimal hello world app testlib
- Upload to to _conan_  with `conan upload -r conan testlib/1.0/myuser/testing --all` ✅ 
   It shows up in nexus
- Try to use it in simple testing project.
  - requirements file: `testlib/1.0/myuser/testing`
  - install requirements with `conan install` ❌ `ERROR: testlib/1.0/myuser/testing was not found in remote 'conan'`
- Try to use a package from proxy
  - requirements file: `Poco/1.8.1@pocoproject/stable`
  - install requirements with `conan install` ✅ 
    - files are downloaded to proxy repo, shows up in the same way as testlib in _conan_ repository
    - packages are downloaded as well

We were suspicios because in nexus ui the path is inverted in the tree (pocoproject ➡️ Poco ➡️ 1.8.1 ➡️ ...) so we try it again and it works the second time too without a redownload from conan-central.

**Comment by doddi** [comment]
@lioman would you mind explaining a little further what you mean here
"We were suspicios because in nexus ui the path is inverted in the tree (pocoproject ➡️ Poco ➡️ 1.8.1 ➡️ ...) so we try it again and it works the second time too without a redownload from conan-central."

Are you saying that the first time you used proxy it failed to retrieve the library but the second time it worked?

FYI the ordering in the UI is purely for display purposes to match how we typically display components, i.e. Group, Artifact, Version (GAV)

**Comment by remgodow** [comment]
I have a similar issue but with just the hosted repository.
I sniffed the traffic in Wireshark and conan client (v 1.8.3) requests url /repository/conan-hosted/v1/conans/OpenSSL/1.1.1/conan/stable/download_urls (results in 404 not found) however in nexus this is stored under url /repository/conan-hosted//v1/conans/**conan**/OpenSSL/1.1.1/stable/download_urls

**Comment by ilyakrasnovsky** [comment]
Same issue here.

**Comment by doddi** [comment]
@lioman @remgodow @ilyakrasnovsky I have created a branch `NEXUS-30-hosted-path-incorrect` which I believe should fix your issue. I would appreciate it if you could test it while it is under review.

**Comment by remgodow** [comment]
I have tested your commit and is seems like it fixed the issue.

**Comment by ilyakrasnovsky** [comment]
I don't think it fixed it completely for me, I'm able to download the `conanmanifest.txt` and the `conanfile.py` (which I wasn't able to before), but then I get the `not found in remote 'conan-internal'` error on `conan_export.tgz`. For reference, I'm using the `NEXUS-30-hosted-path-incorrect` branch with `NEXUS_VERSION` set to `3.12.1` (not `3.13.0`). That should still work right, since the README says that `nexus-repository-conan` version `0.0.3` should work with `NEXUS_VERSION` `3.11.0+`? Thanks so much for the quick responses!

**Comment by ilyakrasnovsky** [comment]
Although running the command again worked. One sec, I'll double check

**Comment by ilyakrasnovsky** [comment]
Ok, I'm able to consistently have it work from command line, so :+1:  - I think my issue was an incredibly underpowered test VM that I was running the docker daemon on, with this on top. I'm not sure I understand the difference between download_urls and Nexus Browse though. Is there ever a use case to download Conan packages through the Nexus UI?

**Comment by ilyakrasnovsky** [comment]
Quick follow up from more extended usage - I am able to get download to work, but often only by running `conan install` **twice**. On the first invocation it always claims `was not found in remote` when processing `conan_export.tgz`, and then the second invocation works fine.

**Comment by remgodow** [comment]
Indeed, second invocation works fine, but for some reason it does not download conan_export.tgz, probably its why it succeds (I wonder if it will have any side effects). Shall we create a new issue for conan_export.tgz problems?

**Comment by doddi** [comment]
Thank you for the clarification @ilyakrasnovsky and @remgodow. I would appreciate it if the conan_export.tgz was raised as a new ticket for traceability. I haven't tried this since @ilyakrasnovsky reported it but I didnt recall having it fail and needing a second `install` to succeed.
A wild guess but I am wondering if it might be a version of the client, if you could add the version you are using to the new ticket that would be useful.

**Comment by EkremH** [comment]
@doddi My team is hitting the same problem with Nexus & Conan. When do you think this PR will be merged?

**Comment by doddi** [comment]
@EkremH I apologise for not seeing this PR through quicker. Unfortunately I am only allocated to work on projects such as this once every 2 weeks. I currently have a backlog of others items. I am sure I will be able to take a look before the year is out.
@DarthHater maybe you could take a look sooner?

**Comment by DarthHater** [comment]
I can take a gander, for sure! Thanks for tagging me @doddi
