### ISSUE TITLE
0.0.4 not compatible with Conan from 1.14.0

### ISSUE THREAD

**Issue by JigsawCorp** [sonatype-nexus-community/nexus-repository-conan#60]
* **What are you trying to do?**
I am trying to use nexus-repositoryy-conan 0.0.4 with Conan 1.14.0 and up.

* **What feature or behavior is this required for?**
This is required for installing packages.

* **How could we solve this issue? (Not knowing is okay!)**
Version 0.0.4 of nexus-repository-conan is not compatible with Conan starting at Conan 1.14.0. The problem is that Conan 1.14.0 started doing a get request to `/v1/conans/{${PROJECT}}/{${VERSION}}/{${GROUP}}/{${STATE}}//packages/{${DIGEST}}`.

It seems that this request returns a 404 from the server.

After looking at your code, I can see that in `src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy`, the endpoint for` /v1/conans/{${PROJECT}}/{${VERSION}}/{${GROUP}}/{${STATE}}//packages/{${DIGEST}}` is not implemented. It seems like a call to this route has only been added in Conan 1.14.0. We would need to update this repo to add this endpoint, otherwise Conan 1.14.0+ users cannot use nexus-repository-conan.
* **Anything else?**

**Comment by sciffer** [comment]
Just ran into this issue as well, as of now - without the support for this URL - the highest supported conan client version is 1.13.3.

**Comment by earonesty** [comment]
For reference:

The endpoint has been present in the conan reference server implementation since the first version (0.4.0), it was just never mandatory before the 1.14.0 was released.   The python source function to search for is `get_package_snapshot` if you want to look at the code.

The response from this endpoint is a dict with a filename key and an md5sum value:

`{"conaninfo.txt":"db64aac5f26459d66cdee20c26304c9a","conan_package.tgz":"24be20028add2ed506d4702788bea822","conanmanifest.txt":"7a79500e4d4a76ca4fe65dc672cbaa82"}`
